---
title: "CA Population Prediction"
output: html_notebook
---

```{r}
# Import libraries
library(tidyr)
library(reshape2)
library(readr)
library(ggplot2)

# import raw data into the data frame
raw_data <- read_csv("Raw Data.csv")
```
```{r}
# Creates new data frame with only the California state
ca <- raw_data[raw_data$STATE == "6", 8:17]
print(ca)
```

```{r}
# Transform from wide to narrow table
df <- melt(ca, variable.name = "Year", value.name = "Population")
str(df)
```
```{r}
# Convert factor variable into numeric in order to graph on ggplot2
df$Year <- as.numeric(df$Year)
```


```{r}
print(df)
```

```{r}
summary(df)
```

```{r}
# Scatterplot
options(scipen = 999)

plot1 <- ggplot(df, aes(x=Year, y=Population)) + geom_point(size=2) + geom_smooth(method="lm", se=FALSE)
plot1
```

```{r}
# Creating a linear regression model
m1 <- lm(Population ~ Year, data=df)

# summary of the linear regression model
summary(m1)
```
```{r}
# Predicting the population size for the next 10 years based on our linear regression model
p_year <- data.frame(Year=c(11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21))
predict(m1, newdata = p_year)
```